/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as GameRouteImport } from './routes/game'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/participants': typeof ParticipantsRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/participants': typeof ParticipantsRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/participants': typeof ParticipantsRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/game'
    | '/groups'
    | '/join'
    | '/lobby'
    | '/login'
    | '/participants'
    | '/profile'
    | '/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/dashboard'
    | '/game'
    | '/groups'
    | '/join'
    | '/lobby'
    | '/login'
    | '/participants'
    | '/profile'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/dashboard'
    | '/game'
    | '/groups'
    | '/join'
    | '/lobby'
    | '/login'
    | '/participants'
    | '/profile'
    | '/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  GameRoute: typeof GameRoute
  GroupsRoute: typeof GroupsRoute
  JoinRoute: typeof JoinRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  ParticipantsRoute: typeof ParticipantsRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  GameRoute: GameRoute,
  GroupsRoute: GroupsRoute,
  JoinRoute: JoinRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  ParticipantsRoute: ParticipantsRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
